/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class JFConverter extends javax.swing.JFrame {

    /**
     * Creates new form JFConverter
     */
    public JFConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JFormattedTextField();
        txtWord = new javax.swing.JTextField();
        txtRoma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        btnConvert.setText("Convert >>");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, 20));

        jLabel2.setText("Word");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        txtNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, -1));
        getContentPane().add(txtWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 420, -1));
        getContentPane().add(txtRoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 420, -1));

        jLabel3.setText("Roman");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        setSize(new java.awt.Dimension(704, 168));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
    if(!txtNum.getText().equals(""))
    {
        //Convert Num to Word
        txtWord.setText("");
        //convert
        NumberWordConverter con=new NumberWordConverter();
        txtWord.setText(con.convertToWord(txtNum.getText()));
       
        NumberRomanConverter conn = new NumberRomanConverter();
        txtRoma.setText(conn.convertToWord(txtNum.getText()));
        txtNum.setText("");
    }
    else if(!txtWord.getText().equals("")) 
    {
        //Convert Word To Num
        txtNum.setText("");
        //Convert
        txtWord.setText("");
    }
    else {JOptionPane.showMessageDialog(null, "Please, insert a number.");}
    }//GEN-LAST:event_btnConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new JFConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtNum;
    private javax.swing.JTextField txtRoma;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
